/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import static Main.main.Preguntas;
import java.awt.event.ActionEvent;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno Tarde
 */
public class VentanaTest extends javax.swing.JFrame {

    int preguntaContador = 0;
    // Hago una lista para almacenar y manejar las respuestas marcadas por el usuario
    ArrayList<Integer> Marcadas = new ArrayList<Integer>();
    // Inicio la aplicación poniendo las preguntas correspondientes
    ArrayList<Pregunta> P = Preguntas(VentanaOpciones.dificultad);
    ArrayList<Respuesta> R = main.Respuestas(P.get(preguntaContador).getId());

    public VentanaTest() throws SQLException {
        initComponents();

        if (preguntaContador < VentanaOpciones.dificultad) {
            jLabel2.setText(P.get(preguntaContador).getPregunta());
            jRadioButton1.setText(R.get(0).getPregunta());
            jRadioButton2.setText(R.get(1).getPregunta());
            jRadioButton3.setText(R.get(2).getPregunta());
        }

    }

    // Declaro aquí las imágenes usadas en la ventana
    ImageIcon ImgMario = new ImageIcon("src/images/Mario (1).png");
    Icon iconoMario = new ImageIcon(ImgMario.getImage());
    ImageIcon imagenAuto = new ImageIcon("src/images/CocheListo.png");
    Icon iconoAuto = new ImageIcon(imagenAuto.getImage());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jRadioButton1.setBackground(new java.awt.Color(51, 102, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setBackground(new java.awt.Color(51, 102, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setBackground(new java.awt.Color(51, 102, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jRadioButton3.setText("jRadioButton3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<Pregunta>");

        jButton1.setText("INSERTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(iconoMario);

        jLabel3.setIcon(iconoAuto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // Guardo la respuesta seleccionada y paso a la siguiente pregunta
        
         if (jRadioButton1.isSelected()||jRadioButton2.isSelected()||jRadioButton3.isSelected()) {
        if (preguntaContador == Marcadas.size() && Marcadas.size() < P.size()) {
            
            if (jRadioButton1.isSelected()) {
                
                Marcadas.add(0);
                preguntaContador++;
            } else if (jRadioButton2.isSelected()) {
                Marcadas.add(1);
                preguntaContador++;
            } else if (jRadioButton3.isSelected()) {

                Marcadas.add(2);
                preguntaContador++;
            }
         
            if (preguntaContador < VentanaOpciones.dificultad) {
                jLabel2.setText(P.get(preguntaContador).getPregunta());
                try {
                    R = main.Respuestas(P.get(preguntaContador).getId());
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaTest.class.getName()).log(Level.SEVERE, null, ex);
                }
                jRadioButton1.setText(R.get(0).getPregunta());
                jRadioButton2.setText(R.get(1).getPregunta());
                jRadioButton3.setText(R.get(2).getPregunta());
                 jRadioButton1.setSelected(false);
                 jRadioButton2.setSelected(false);
                 jRadioButton3.setSelected(false);
            }
                
                
        } else if (preguntaContador < Marcadas.size() ) {
           if (jRadioButton1.isSelected()) {
               
                Marcadas.set(preguntaContador,0);
                preguntaContador++;
            } else if (jRadioButton2.isSelected()) {
                Marcadas.set(preguntaContador,1);
                preguntaContador++;
            } else if (jRadioButton3.isSelected()) {

                Marcadas.set(preguntaContador,2);
                preguntaContador++;
            }
            if (preguntaContador < VentanaOpciones.dificultad) {
                jLabel2.setText(P.get(preguntaContador).getPregunta());
                jRadioButton1.setText(R.get(0).getPregunta());
                jRadioButton2.setText(R.get(1).getPregunta());
                jRadioButton3.setText(R.get(2).getPregunta());
                
                if (Marcadas.get(preguntaContador)==0) {
                     jRadioButton1.setSelected(true);
                 jRadioButton2.setSelected(false);
                 jRadioButton3.setSelected(false);
                } else if(Marcadas.get(preguntaContador)==1) {
                     jRadioButton1.setSelected(false);
                 jRadioButton2.setSelected(true);
                 jRadioButton3.setSelected(false);
                }else if(Marcadas.get(preguntaContador)==2){
                       jRadioButton1.setSelected(false);
                 jRadioButton2.setSelected(true);
                 jRadioButton3.setSelected(false);
                }
                
            }

        } else if (Marcadas.size() == P.size()) {
            int aciertos = 0;
            for (int i = 0; i < P.size(); i++) {
                if (R.get(Marcadas.get(i)).getCorrecta() == 0) {
                    aciertos++;
                }

            }
            JOptionPane.showMessageDialog(null, "Aciertos:" + aciertos + "/" + P.size());
            setVisible(false);

        }

         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new VentanaTest().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaTest.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables

}
